#include "std_types.h"
#include "bit_math.h"
#include "MDIO_Registers.h"
#include "MPORT_PBCFG.h"
#include "MPORT.h"
#include "MPORT_LCFG.h"


// array that stores pin configuration and sets it at runtime
MPORT_structPortPinDirAndMode_t MDIO_enuArrPinConfig[MPORT_NUM_OF_ALL_PINS] = 
{
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_NONE},
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_NONE},
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_NONE},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_INPUT, MPORT_PIN_MODE_INPUT_PULLDOWN},
    {MPORT_PORT_PIN_OUTPUT, MPORT_PIN_MODE_NONE}
};
